[View in Colaboratory](https://colab.research.google.com/github/rodgzilla/notebook_sharing/blob/master/dropout_noise_shape.ipynb)

In [0]:
import tensorflow as tf
import numpy as np
import tensorflow.contrib.eager as tfe
tfe.enable_eager_execution()

In [0]:
tensor_shape = (3, 2, 4)
keep_rate = 0.8

In [0]:
tensor = tf.convert_to_tensor(np.random.randn(*tensor_shape))
tensor

<tf.Tensor: id=1, shape=(3, 2, 4), dtype=float64, numpy=
array([[[ 1.42035596,  1.66541823, -0.20575664,  0.17418224],
        [-2.42670931, -0.64577029,  0.96537531,  0.09581659]],

       [[-1.02561263,  0.29393466, -0.09881811, -0.91015902],
        [-0.04531573,  0.94318948, -0.79369668, -0.18290456]],

       [[ 0.07300701,  0.21344522, -1.21499859, -0.7039356 ],
        [-2.00403841, -0.16495453, -1.25145647, -0.34425731]]])>

In [0]:
shape = [dim.value for dim in tensor.shape]
shape

[3, 2, 4]

In [0]:
dropout_shape = shape[:]
dropout_shape[1] = 1
print(dropout_shape)
dropout_result = tf.nn.dropout(tensor, keep_rate, dropout_shape)
dropout_result

[3, 1, 4]


<tf.Tensor: id=14, shape=(3, 2, 4), dtype=float64, numpy=
array([[[ 0.        ,  2.08177279, -0.        ,  0.2177278 ],
        [-0.        , -0.80721287,  0.        ,  0.11977074]],

       [[-0.        ,  0.36741832, -0.12352263, -1.13769877],
        [-0.        ,  1.17898685, -0.99212085, -0.2286307 ]],

       [[ 0.09125876,  0.        , -1.51874824, -0.8799195 ],
        [-2.50504802, -0.        , -1.56432058, -0.43032164]]])>

In [0]:
dropout_shape = shape[:]
dropout_shape[1] = dropout_shape[2] = 1
print(dropout_shape)
dropout_result = tf.nn.dropout(tensor, keep_rate, dropout_shape)
dropout_result

[3, 1, 1]


<tf.Tensor: id=24, shape=(3, 2, 4), dtype=float64, numpy=
array([[[ 1.77544495,  2.08177279, -0.2571958 ,  0.2177278 ],
        [-3.03338664, -0.80721287,  1.20671914,  0.11977074]],

       [[-0.        ,  0.        , -0.        , -0.        ],
        [-0.        ,  0.        , -0.        , -0.        ]],

       [[ 0.09125876,  0.26680652, -1.51874824, -0.8799195 ],
        [-2.50504802, -0.20619317, -1.56432058, -0.43032164]]])>